name: Matrix Lab
on:
  workflow_dispatch:

jobs:
  matrix-job:
    strategy:
      max-parallel: 2
      matrix:
        os: [windows-latest, ubuntu-latest]
        node: [14, 16]
        include:
          - os: windows-latest
            node: 16
            npm: 6
            
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3.9.1
        with:
          node-version: ${{matrix.node}}
      - if: ${{matrix.npm}}
        run: npm install -g npm@${{ matrix.npm }}
      - run: npm --version
