# This is a basic workflow to help you get started with Actions

name: Matrix lab

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  matrix-job:
    strategy:
    matrix:
      os: [windows-latest, ubuntu-latest]
      node: [14, 16]
    runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/setup-node@v3.9.1
          with:
            node-version: ${{ matrix.node }}
